# Generated by Django 5.0.7 on 2024-07-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_product_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
